[tool.poetry]
name = "model_download"
version = "0.1.0"
description = "A FastAPI application for downloading and converting Hugging Face models."
authors = ["Saranya, Anbuchezhiyan <saranya.a@intel.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "0.115.4"
uvicorn = "^0.23.2"
structlog = "25.1.0"
huggingface_hub = "0.27.1"

[build-system]
requires = ["poetry-core>=1.8.3"]
build-backend = "poetry.core.masonry.api"